### ISSUE TITLE
Lots of empty set comands

### ISSUE THREAD

**Issue by binarykitchen** [DavidWells/analytics#176]
`Running command: ga("set", {})`
`Running command: ga("set", {})`
`Running command: ga("set", {})`
`Running command: ga("set", {})`

Seeing lots of these, setting nothing with empty parameters. Why and where do they come from. What's missing?

**Comment by DavidWells** [comment]
Interesting it might be this line https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/browser.js#L130-L131

Is `analytics.user()` set with values? 

We might need to noOp this if it's problematic & the traits aren't mapped

**Comment by binarykitchen** [comment]
Yes `analytics.user()` returns an object. It's set with the analytics.identify() fn in my code but without dimensions.

Yes please don't set when `customDimensions` is null for whatever reasons.

**Comment by DavidWells** [comment]
Fixed with `@analytics/google-analytics@0.5.3`

**Comment by binarykitchen** [comment]
thanks!

**Comment by binarykitchen** [comment]
@DavidWells afraid some is still happening on v0.5.3
![Screen Shot 2021-08-05 at 14 51 53](https://user-images.githubusercontent.com/177641/128283405-9504cd0c-f4a8-4791-87a1-faf86f60ad8d.png)
